@startuml
title BPMN (Activity): Обработка запроса

header
--------------------------------------------------------------
| Наименование документа: | BPMN (Activity) диаграмма "Обработка запроса" |
| Тема проекта:            | Описание работы ИТ-вендора в рамках поддержки решений |
| Исполнитель:             | John Smith                                |
| Дата:                    | 14.02.2025                                |
| Стандарт:                | ГОСТ Р 19.101-77                           |
| Трассируемость:          | Часть 3/6 – Детализация процессов           |
| Задача диаграммы:        | Детализировать последовательность операций, |
|                         | включая ветвление для критичных заявок      |
--------------------------------------------------------------
end header

start
:Получение запроса;
:Регистрация запроса;
:Оценка заявки (критическая/не критическая);
if (Заявка критическая?) then (Да)
  :Передача на диагностику;
endif
:Диагностика заявки;
:Принятие решения;
:Проверка заявки на наличие дисфункций;
:Закрытие заявки;
stop
@enduml
