@startuml
title EPC: Обработка запроса

header
--------------------------------------------------------------
| Наименование документа: | EPC-диаграмма "Обработка запроса"         |
| Тема проекта:            | Описание работы ИТ-вендора в рамках поддержки решений |
| Исполнитель:             | John Smith                                |
| Дата:                    | 14.02.2025                                |
| Стандарт:                | ГОСТ Р 19.101-77                           |
| Трассируемость:          | Часть 2/6 – Процессное моделирование         |
| Задача диаграммы:        | Показать последовательность этапов от      |
|                         | получения до закрытия запроса              |
--------------------------------------------------------------
end header

(*) --> "Получение запроса"
"Получение запроса" --> "Запрос получен"
"Запрос получен" --> "Регистрация запроса"
"Регистрация запроса" --> "Запрос зарегистрирован"
"Запрос зарегистрирован" --> "Оценка заявки (критическая/не критическая)"
"Оценка заявки (критическая/не критическая)" --> "Приоритет определён"
"Приоритет определён" --> "Диагностика запроса"
"Диагностика запроса" --> "Диагностика завершена"
"Диагностика завершена" --> "Принятие решения"
"Принятие решения" --> "Решение принято"
"Решение принято" --> "Проверка на дисфункции"
"Проверка на дисфункции" --> "Проверка завершена"
"Проверка завершена" --> "Закрытие заявки"
"Закрытие заявки" --> "Запрос закрыт"
"Запрос закрыт" --> (*)
@enduml
