@startuml
title UML Use Case Diagram: Поддержка решений

header
--------------------------------------------------------------
| Наименование документа: | UML Диаграмма Прецедентов "Поддержка решений" |
| Тема проекта:            | Описание работы ИТ-вендора в рамках поддержки решений |
| Исполнитель:             | John Smith                                |
| Дата:                    | 14.02.2025                                |
| Стандарт:                | ГОСТ Р 19.101-77                           |
| Трассируемость:          | Часть 5/6 – Моделирование взаимодействий      |
| Задача диаграммы:        | Описать роли и взаимодействия (Клиент, Оператор,|
|                         | Инженер, ИТ-система, Менеджер) в процессе поддержки |
--------------------------------------------------------------
end header

actor "Клиент" as ClientActor
actor "Оператор поддержки" as SupportActor
actor "Инженер" as EngineerActor
actor "ИТ-система" as ITSystemActor
actor "Менеджер" as ManagerActor

ClientActor --> ("Получение запроса")
ClientActor --> ("Отправка запроса")
SupportActor --> ("Регистрация запроса")
SupportActor --> ("Оценка заявки – критическая или не критическая")
EngineerActor --> ("Диагностика заявки")
ITSystemActor --> ("Проверка заявки на дисфункции")
SupportActor --> ("Принятие решения")
SupportActor --> ("Закрытие заявки")
ManagerActor --> ("Контроль качества")
@enduml
